### ISSUE TITLE
Here WeGo url format

### ISSUE THREAD

**Issue by ZhiJianTan** [ZhiJianTan/MapSwitcher#1]
Additional url format for web domain Here WeGo needs to be implemented so the extension icon will popup

**Comment by waiwai1000** [comment]
ok, will look into it

**Comment by ZhiJianTan** [comment]
Thanks. I think will need to look inside map.js file and add in url's for the extension to recognize

**Comment by ZhiJianTan** [comment]
Extension now recognizes normal and satellite maps on HereWeGo

**Comment by ZhiJianTan** [comment]
Tested to work with different map types. closing issue.
